config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("invoice.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
    settings.STATIC_URL,
    document_root = settings.STATIC_ROOT
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

invoice/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("form", views.get_product, name="form"),
    path("products/", views.ProductsPageView.as_view(), name="products"),
    # path("invoicepdf", views.InvoicePdfView.as_view(), name="invoice"),
    path("add-product-item/", views.add_new_product_item_view, name="add-item"),
    path("add-product/", views.add_new_product_view, name="add-product"),
    path("sales-report", views.OrderView.as_view(), name="sales-report"),
    path("", views.HomePageView.as_view(), name="invoice")
]

invoice/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Category"


class Product(models.Model):
    name = models.CharField(max_length=250, null=True)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class ProductItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media/")
    description = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    code = models.CharField(max_length=20)
    price = models.IntegerField()
    available = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.product} | {self.code}'

    class Meta:
        ordering = ('-date',)




class Size(models.Model):
    product_item = models.ForeignKey(ProductItem, on_delete=models.CASCADE)
    size = models.CharField(max_length=6, null=True)
    quantity = models.IntegerField(null=True)


status_choices = [
    ("Pending", "Pending"),
    ("Delivered", "Delivered"),
    ("Courier", "Courier"),
    ("Exchange", "Exchange"),
    ("Cancel", "Cancel"),
    ("Return", "Return"),
]

courier_choices = [
    ("Pathao", "Pathao"),
    ("RedX", "RedX"),
]

delivery_charge = [
    (70, "Inside Dhaka"),
    (130, "Outside Dhaka"),
]

class Customer(models.Model):
    name = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    mobile = models.IntegerField()
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    status = models.CharField(max_length=20, choices=status_choices, default="Delivered")
    invoice_no = models.IntegerField()
    parcel_id = models.CharField(max_length=250, blank=True, null=True)
    products = models.ManyToManyField(ProductItem, related_name="order", )
    delivery_charge = models.DecimalField(max_digits=7, decimal_places=2,choices=delivery_charge)
    courier_charge = models.DecimalField(max_digits=7, decimal_places=2)
    invoice_amount = models.DecimalField(max_digits=7, decimal_places=2)
    receivable_amount = models.DecimalField(max_digits=7, decimal_places=2)
    courier_type = models.CharField(max_length=10, choices=courier_choices, default="Pathao")
    order_by = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f'Order: {self.created_on.strftime("%b %d %Y %I:%M %p")}'



    class Meta:
        ordering = ("-created_on",)

invoice/forms.py
from django.forms import ModelForm
# from django.conf import settings
# from django.template.loader import get_template
# from xhtml2pdf import pisa
from django import forms
from django.forms.models import inlineformset_factory

from .models import Product, ProductItem, Size, Order

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ["slug"]


class ProductItemForm(forms.ModelForm):
    class Meta:
        model = ProductItem
        exclude = ["date", "slug"]

SizeFormSet = inlineformset_factory(
    ProductItem,
    Size,
    form=ProductItemForm,
    fields=("size", "quantity"),
    extra=6,
)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["date", "slug"]

invoice/views.py
from django.views.generic import TemplateView, ListView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Category, Product, ProductItem, Order
from .forms import ProductForm, ProductItemForm, SizeFormSet

class HomePageView(TemplateView):
    """Home Page View"""
    template_name = "index.html"

def add_new_product_view(request):
    context = {}
    form = ProductForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/add-product/')
    else:
        form = ProductForm()

    context['form'] = form
    return render(request, "add_product.html", context)


def add_new_product_item_view(request):
    context = {}
    form = ProductItemForm(request.POST or None, request.FILES or None)
    formset = SizeFormSet(request.POST or None)

    if form.is_valid() and formset.is_valid():
        product = form.save()
        for form in formset:
            size = form.save(commit=False)
            size.product_item = product
            size.save()

        return HttpResponseRedirect('/products/')
    else:
        form = ProductItemForm()

    context['form'] = form
    context['formset'] = formset
    return render(request, "add_product_item.html", context)

class ProductsPageView(ListView):
    model = ProductItem
    context_object_name = "productitems"
    template_name = "products.html"

class OrderView(ListView):
    model = Order
    context_object_name = "invoices"
    template_name = "history.html"

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Eazzl | Invoice</title>

   <!-- StyleSheet -->
    <link rel="stylesheet" href="{% static "css/style.css" %}" />

    <!-- Favicon -->
    <!-- <link -->
    <!--   rel="shortcut icon" -->
    <!--   href="{% static "images/favicon/favicon-32x32.png" %}" -->
    <!--   type="image/x-icon" -->
    <!-- /> -->


    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

    <!-- Javascript -->
    <script defer src="{% static "js/app.js" %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">


  </head>
  <body>

    <div class="container">
    <div class="logo">
    <a class="text-center" href="{% url "invoice" %}">
      <img class="img-fluid mx-auto d-block"
        src="{% static "images/logo-m.svg" %}" alt="EAZZL" />
    </a>
    </div>

 {% block content %}

    {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

  </body>
</html>

templates/add_new.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<div class="add-invoice container">
  <h2>Create A New Invoice</h2>
  <form class="row g-3">
    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="date" class="col-form-label">Date:</label>
      </div>
      <div class="col-auto">
        <input type="date" id="date" class="form-control">
      </div>
    </div>

    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="status" class="col-form-label">status:</label>
      </div>
      <div class="col-auto">
        <select class="form-select">
          <option selected>Click to select menu</option>
          <option value="1">Delivered</option>
          <option value="2">Pending</option>
          <option value="3">Return</option>
          <option value="4">Exchange</option>
          <option value="5">Courier</option>
          <option value="6">Cancel</option>
        </select>
      </div>
    </div>

    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="invoice-no" class="col-form-label">Invoice No.:</label>
      </div>
      <div class="col-auto">
        <input type="text" id="invoice-no" class="form-control">
      </div>
    </div>

    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="parcel-id" class="col-form-label">Parcel ID:</label>
      </div>
      <div class="col-auto">
        <input type="text" id="parcel-id" class="form-control">
      </div>
    </div>

    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="customer-name" class="col-form-label">Customer Name:</label>
      </div>
      <div class="col-auto">
        <input type="text" id="customer-name" class="form-control">
      </div>
    </div>

    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="customer-address" class="col-form-label">Customer Address:</label>
      </div>
      <div class="col-auto">
        <input type="text" id="customer-address" class="form-control">
      </div>
    </div>

    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label for="mobile" class="col-form-label">Mobile Number:</label>
      </div>
      <div class="col-auto">
        <input type="number" id="mobile" class="form-control">
      </div>
    </div>
    <div class="items row g-3">
    <p>Items:</p>
    </div>
    <button class="btn add-items">Add items</button>

    <button type="submit" class="btn btn-primary">Submit</button>

  </form>
</div>
{% endblock content %}

templates/add_product.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<div class="container">
<h1>Add New Product</h1>
<form action="/add-product/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
</div>

{% endblock %}

templates/add_product_item.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<h1>Add New Product Item</h1>
<form action="/add-product-item/" method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form.as_p }}
    {% for form in formset.forms %}
        <table class='no_error'>
            {{ form.as_table }}
        </table>
    {% endfor %}

    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/form.html
<form action="/form/" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
</form>

templates/history.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<table>
  <tr>
  <th class="border"> Date </th>
  <th class="border"> Status </th>
  <th class="border"> Invoice NO </th>
  <th class=" border"> Parcel Id </th>
  <th class=" border"> Customer Name </th>
  <th class=" border"> Customer Address </th>
  <th class=" border"> Customer Mobile </th>
  <th class=" border"> Items </th>
  <th class=" border"> Delivery Charge </th>
  <th class=" border"> Courier Charge </th>
  <th class=" border"> Invoice Amount </th>
  <th class=" border"> Recievable Amount </th>
  <th class=" border"> Courier Type </th>
  <th class=" border"> Order By </th>
  </tr>

{% for invoice in invoices %}
  <tr>
  <td class=" border">{{ invoice.created_on }}</td>
  <td class=" border">{{ invoice.status }}</td>
  <td class=" border">{{ invoice.invoice_no }}</td>
  <td class=" border">{{ invoice.parcel_id }}</td>
  <td class=" border">{{ invoice.customer.name}}</td>
  <td class=" border">{{ invoice.customer.address }}</td>
  <td class=" border">{{ invoice.customer.mobile }}</td>

  <td class=" border">
    <table>
  {% for product in invoice.products.all %}
  <tr class="border-big">
    <td class="border">{{ product.name }}</td>
    <td class="border">{{ product.code }}</td>
    <td class="border">{{ product.price }}</td>
    <!-- <p class="col">{{ product.available }}</p> -->
    {% for size in product.size_set.all %}
        <td class="col">{{ size.size }}</td>
        <td class="col">{{ size.quantity }}</td>
    {% endfor %}
</tr>
  {% endfor %}

  </table>
  </td>
  <td class="col border">{{ invoice.delivery_charge }}</td>
  <td class="col border">{{ invoice.courier_charge }}</td>
  <td class="col border">{{ invoice.invoice_amount }}</td>
  <td class="col border">{{ invoice.receivable_amount }}</td>
  <td class="col border">{{ invoice.courier_type }}</td>
  <td class="col border">{{ invoice.order_by }}</td>
  </tr>
  {% endfor %}
</table>
  {% endblock content %}

templates/index.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<div class="invoice">
<a class="row" href="{% url "add-product" %}">
    <button>Add New Product</button>
  </a>

<a class="row" href="{% url "add-item" %}">
    <button>Add New Item</button>
  </a>

<a class="row" href="{% url "products" %}">
    <button>Products</button>
  </a>

<a class="row" href="{% url "sales-report" %}">
    <button>Sales Report</button>
  </a>

</div>


{% endblock content %}

templates/invoice_pdf.html
<!DOCTYPE html>
<html>
<head>
  <title>pdf report</title>
</head>
<body>
  {% block content %}
<div class="row border">
  <p class="col border">{{ invoice.date }}</p>
  <p class="col border">{{ invoice.status }}</p>
  <p class="col border">{{ invoice.invoice_no }}</p>
  <p class="col border">{{ invoice.parcel_id }}</p>
  <p class="col border">{{ invoice.customer_name }}</p>
  <p class="col border">{{ invoice.customer_address }}</p>
  <p class="col border">{{ invoice.customer_mobile }}</p>

  {% for product in invoice.products.all %}
  <span class="col">

    <p class="col">{{ product.name }}</p>
    <p class="col">{{ product.code }}</p>
    <p class="col">{{ product.price }}</p>
    <!-- <p class="col">{{ product.available }}</p> -->
    {% for size in product.sizemodel_set.all %}
    <span class="col border">
      <span class="row">
        <p class="col">{{ size.size }}</p>
        <p class="col">{{ size.quantity }}</p>
      </span>
    </span>
    {% endfor %}
  </span>
  {% endfor %}
  <p class="col border">{{ invoice.delivary_charge }}</p>
  <p class="col border">{{ invoice.courier_charge }}</p>
  <p class="col border">{{ invoice.invoice_amount }}</p>
  <p class="col border">{{ invoice.receivable_amount }}</p>
  <p class="col border">{{ invoice.courier_type }}</p>
  <p class="col border">{{ invoice.order_by }}</p>
  {% endblock content %}

</body>
</html>

templates/products.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<div class="container">
<div class="row row-cols-1 row-cols-md-3 g-4">

{% for product in productitems|dictsortreversed:"date" %}
<div class="col">
  <a style="text-decoration: none;" href="#">
<div class="card" style="width: 20rem;">
  <img height="230px" src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
  <div class="card-body">
    <h5 class="card-title">{{ product.name }}</h5>
    <h6 class="card-text">{{ product.code }}</h6>
    <p class="card-text">{{ product.description }}</p>
    <a href="#" class="btn btn-primary">Add To Cart</a>
  </div>
</div>
  </a>
</div>
{% endfor %}
</div>
</div>

<!-- <table> -->
<!-- <tr> -->
<!--   <th class="border ">Category</th> -->
<!--   <th class="border ">Name</th> -->
<!--   <th class="border ">Image</th> -->
<!--   <th class="border ">Description</th> -->
<!--   <th class="border ">Date</th> -->
<!--   <th class="border ">Code</th> -->
<!--   <th class="border ">Price</th> -->
<!--   <th class="border ">Available</th> -->
<!--   <th class="border ">Sizes</th> -->
<!-- </tr> -->
<!-- {% for product in productitems|dictsortreversed:"date" %} -->

<!-- <tr class="border-big "> -->
<!--   <td class="border ">{{ product.product.category }}</td> -->
<!--   <td class="border ">{{ product.product }}</td> -->
<!--   <td class="border "><img src="{{ product.image.url }}" alt="{{ prdouct.name }}" width="50px" height="50px" /></td> -->
<!--   <td class="border ">{{ product.description }}</td> -->
<!--   <td class="border ">{{ product.date }}</td> -->
<!--   <td class="border ">{{ product.code }}</td> -->
<!--   <td class="border ">{{ product.price }}</td> -->
<!--   <td class="border ">{{ product.available }}</td> -->
<!--   <td class="border "> -->
<!--   {% for size in product.size_set.all %} -->
<!--   <table> -->
<!--     <tr class="border "> -->
<!--     <td>{{ size.size }} </td> -->
<!--     <td> - {{ size.quantity }}</td> -->
<!--     </tr> -->
<!--   </table> -->
<!--   {% endfor %} -->
<!--   </td> -->
<!--   </tr> -->
<!-- {% endfor %} -->

<!-- </table> -->
{% endblock content %}